services:
  rabbitmq-broker:
    image: rabbitmq:4-management@sha256:8f3ab1dc6fb3b17ff59ba4e9ceed187c1711a4af831242b733b1e6949625b315
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # the port RabbitMQ will listen on
      - "15672:15672" # the port the dashboard web service will be available from

  postgres-db:
    image: postgres:18.3@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./storage/src/main/resources/ddl-scripts/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
