services:
  rabbitmq-broker:
    image: rabbitmq:4-management@sha256:693b2012f0823c3b75e75e9e6248426e9dc1802e748b5e8deddaa71602c4383b
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # the port RabbitMQ will listen on
      - "15672:15672" # the port the dashboard web service will be available from

  postgres-db:
    image: postgres:18.3@sha256:d97e12178dfeddd3ed303eae53de1f556b20e7e42c68db809aa33f6527b3ab2b
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./storage/src/main/resources/ddl-scripts/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
