name: Continuous Integration and Delivery

on:
  workflow_call:
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.USERNAME }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14, windows-2022 ]
        jvm-version: [ 17, 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK ${{ matrix.jvm-version }}
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm-version }}
      - name: Assemble main and test classes
        run: ./gradlew classes testClasses
      - name: Test
        run: ./gradlew test
      - name: Check
        run: ./gradlew check
      - name: Generate fatjar
        run: ./gradlew entrypoint:shadowJar
      - name: Upload fatjar
        if: ${{ contains(matrix.os, 'ubuntu') && matrix.jvm-version == 21 }}
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: app-fatjar
          path: entrypoint/build/libs/*.jar
          if-no-files-found: error

  dry-delivery:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Download fatjar from uploaded artifact
        uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43 # v7
        with:
          workflow: dispatcher.yml
          workflow_conclusion: in_progress
          commit: ${{ github.sha }}
          name: app-fatjar
          path: entrypoint/build/libs/
      - run: ls entrypoint/build/libs/
      - name: Build dockerfile
        run: docker build .

  release:
    needs: dry-delivery
    if: github.ref_name == github.event.repository.default_branch
    permissions: # Not specified scopes are set to `none`!
      packages: write
      contents: write
      issues: write
      pull-requests: write
    concurrency:
      group: release-and-delivery-${{ github.event.number || github.ref }}
    runs-on: ubuntu-24.04
    outputs: # see release.config.js
      release-status: ${{ env.RELEASE_STATUS }}
      release_version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true
      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT
      - name: Install Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.POSITION_PAL_BOT_TOKEN }}

  publish-images:
    needs:
      - release
    # Trigger this job only if the semantic release bot has released a new version
    if: ${{ needs.release.outputs.release-status == 'released' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3
      - name: Download fatjar from uploaded artifact
        uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43 # v7
        with:
          workflow: dispatcher.yml
          workflow_conclusion: in_progress
          commit: ${{ github.sha }}
          name: app-fatjar
          path: entrypoint/build/libs/
      - name: Build and push
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.release.outputs.release_version }}

  publish-doc:
    needs:
      - release
    # Trigger this job only if the semantic release bot has released a new version
    if: ${{ needs.release.outputs.release-status == 'released' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ needs.release.outputs.release_version }}
          fetch-tags: true
      - name: Generate dokka multi-module documentation
        run: ./gradlew dokkaHtmlMultiModule
      - name: Publish on Github pages
        uses: JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a # v4
        with:
          folder: ./build/dokka/htmlMultiModule

  success:
    needs:
      - build
      - dry-delivery
      - release
      - publish-doc
      - publish-images
    if: >- # run if at least one needed job has failed or all needed jobs have not been cancelled
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    runs-on: ubuntu-24.04
    steps:
      - name: Verify no failures occurred in needed jobs
        # if there are failures, false is executed and the job fails.
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}